name: Build & Push Salad SN-27 image

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/Dockerfile"
      - "**/entrypoint.sh"
      - "**/requirements.txt"
      - ".github/workflows/docker.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write       # needed for GHCR push
    steps:
      - uses: actions/checkout@v4

      - name: Set image name
        id: vars
        run: echo "IMAGE ghcr.io/${{ github.repository }}:latest" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.IMAGE }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max
